name: 🎈 Publish
on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔬 Lint
        run: yarn run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🔎 Type check
        run: yarn run typecheck --if-present

  deploy:
    name: 🚀 Publish
    runs-on: ubuntu-latest
    needs: [lint, typecheck]
    # only build/deploy main branch on pushes
    if: ${{ (github.ref == 'refs/heads/main') &&
      github.event_name == 'push' }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm publish
        env:
          NPM_SECRET: ${{ secrets.NPM_SECRET }}
